# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
target 'XXBNavDemo' do
pod 'XXBLibs', :git => "https://github.com/sixTiger/XXBLibs"
end
target 'XXBNavDemoTests'  do
end

